import Head from 'next/head'

import { Card } from '@components/Card'
import { SectionFilter } from '@components/SectionFilter'

import styles from './styles.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home | Comprar carros usados no brasil</title>
      </Head>
      <SectionFilter />
      <section>
        <div className={styles.app_layout_home_content}>
          <div className={styles.app_layout_home_content_cards}>
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </div>
        </div>
      </section>
    </>
  )
}
