# Generated by Django 4.1.5 on 2023-01-09 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Carros",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("image_url", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("location", models.CharField(max_length=80)),
                ("mileage", models.IntegerField()),
                (
                    "original_value",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "promotional_value",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
            ],
        ),
    ]
