import { GetStaticProps } from 'next'
import Head from 'next/head'

import { Card } from '@components/Card'
import { SectionFilter } from '@components/SectionFilter'

import { ICars } from '@interfaces/ICars'
import { api } from '@services/axios'

import styles from './../styles/Home.module.scss'

interface HomeProps {
  cars: ICars[]
}

export default function Home({ cars }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Home | Comprar carros usados no brasil</title>
      </Head>
      <SectionFilter />
      <section>
        <div className={styles.app_layout_home_content}>
          <div className={styles.app_layout_home_content_cards}>
            {cars.map((car) => (
              <Card
                key={car.id}
                title={car.name}
                location={car.location}
                price={car.original_value}
                mileage={car.mileage}
                year={car.year}
                imageUrl={car.image_url}
              />
            ))}
          </div>
        </div>
      </section>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get<ICars[]>('/carros')

  return {
    props: {
      cars: data,
    },
    revalidate: 60 * 60 * 1, // 1 Hour,
  }
}
